ARG SOLR_VERSION=8
FROM solr:${SOLR_VERSION}

ENV SOLR_PORT=8983

EXPOSE ${SOLR_PORT}

ARG CKAN_BRANCH="dev-v2.10"

ENV SOLR_INSTALL="/opt/solr"
ENV SOLR_CONFIG_DIR="$SOLR_INSTALL/server/solr/configsets"
ENV SOLR_SCHEMA_FILE="$SOLR_CONFIG_DIR/ckan/conf/managed-schema"
ENV SOLR_CKAN_DATABASE=ckan

ARG JTS_VERSION="1.19.0"
ARG JTS_JAR_FILE="$SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/lib/jts-core-$JTS_VERSION.jar"

USER root

# Create a CKAN configset by copying the default one
RUN cp -R $SOLR_CONFIG_DIR/_default $SOLR_CONFIG_DIR/$SOLR_CKAN_DATABASE

# Update the schema
ADD https://raw.githubusercontent.com/ckan/ckan/$CKAN_BRANCH/ckan/config/solr/schema.xml $SOLR_SCHEMA_FILE

# Install JTS JAR file
ADD https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/$JTS_VERSION/jts-core-$JTS_VERSION.jar \
    $JTS_JAR_FILE
RUN chmod 644 $JTS_JAR_FILE

# Apply spatial schema fragments
COPY schema/ /tmp/schema/
RUN sed -i "/<types>/r /tmp/schema/spatial-types.xml" $SOLR_SCHEMA_FILE \
    && cat /tmp/schema/spatial-fields.xml \
           /tmp/schema/dcat-ap-fields.xml \
           /tmp/schema/dcat-ap-es-fields.xml > /tmp/schema/extra-fields.xml \
    && sed -i "/<fields>/r /tmp/schema/extra-fields.xml" $SOLR_SCHEMA_FILE \
    && chmod 644 $SOLR_SCHEMA_FILE

USER solr

CMD ["sh", "-c", "solr-precreate $SOLR_CKAN_DATABASE $SOLR_CONFIG_DIR/$SOLR_CKAN_DATABASE"]
