name: CKAN 2.12 with Solr 10

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish-ghcr-solr.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      ckan_version: "2.12"
      ckan_branch: "dev-v2.12"
      solr_version: "10"
      solr_image_version: "10.0"
