name: CKAN 2.10 with Solr 8

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish-ghcr-solr.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      ckan_version: "2.10"
      ckan_branch: "dev-v2.10"
      solr_version: "8"
      solr_image_version: "8"
